import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;

public class PurpleGuy {
    public static final String line = "\u2500".repeat(50) + "\n";
    public static Scanner inputScan = new Scanner(System.in);
    public static ArrayList<Task> taskList = new ArrayList<>(100);

    // PurpleGuy Design and colours generated by Gemini
    public static final String AFTON_PURPLE = "\u001B[38;2;120;0;200m";
    public static final String DARK_P = "\u001B[48;2;75;0;130m  ";  // Deep Purple
    public static final String V_DARK = "\u001B[48;2;48;0;78m  ";   // Shadow Purple
    public static final String WHITE  = "\u001B[48;2;255;255;255m  "; 
    public static final String BLACK  = "\u001B[48;2;0;0;0m  ";
    public static final String RESET  = "\u001B[0m";
    public static final String S      = "  "; // Empty space
    
    public static void aftonSpeech(String message) {
            System.out.println(AFTON_PURPLE + message + RESET);
    }

    public static void listTasks(){
        for (int i=0; i < taskList.size();i++) {
            aftonSpeech(String.format("%d.%s",(i+1),taskList.get(i)));
        }
    }
    public static void main(String[] args) {

        String[] sprite = {
            S+S+DARK_P+DARK_P+DARK_P+DARK_P,
            S+DARK_P+DARK_P+DARK_P+DARK_P+DARK_P+DARK_P,
            S+WHITE+BLACK+DARK_P+WHITE+BLACK+DARK_P,
            S+DARK_P+DARK_P+DARK_P+DARK_P+DARK_P+DARK_P,
            S+DARK_P+V_DARK+V_DARK+V_DARK+V_DARK+DARK_P+DARK_P+DARK_P,
            S+S+DARK_P+V_DARK+V_DARK+DARK_P+DARK_P+DARK_P+DARK_P,
            S+S+S+S+S+DARK_P+DARK_P+DARK_P+DARK_P,
            S+DARK_P+DARK_P+DARK_P+DARK_P+DARK_P+DARK_P+DARK_P+DARK_P,
            S+S+S+S+S+DARK_P+DARK_P+DARK_P+DARK_P,
            S+S+DARK_P+DARK_P+DARK_P+DARK_P+DARK_P+DARK_P,
            S+S+S+S+S+DARK_P+DARK_P+DARK_P+DARK_P,
            S+S+S+S+S+DARK_P+DARK_P+DARK_P+DARK_P,
            S+S+S+S+S+DARK_P+S+S+DARK_P,
            S+S+S+S+S+DARK_P+S+S+DARK_P,
            S+S+S+S+S+DARK_P+S+S+DARK_P
        };

        for (String body : sprite) {
            System.out.println(body + RESET);
        }
        aftonSpeech("You look... familiar. Have we met at the Pizzeria?");
        aftonSpeech("I'm William. But I suppose you have your own names for me.");
        aftonSpeech("Tell me... why are you really here?\n");

        String userInput = inputScan.nextLine();
        int index;
        String taskName;
        while (!userInput.equals("bye")) {
            String[] caseVars = userInput.split(" ");
            switch (caseVars[0]) {
                case "list":
                    listTasks();
                    System.out.println();
                    break;
                    
                case "mark":
                    index = Integer.parseInt(caseVars[1])-1;
                    Task m_task = taskList.get(index);
                    m_task.mark();
                    aftonSpeech("Done. It's finally... over. For now.");
                    System.out.println(m_task + "\n");
                    break;
                
                case "unmark":
                    index = Integer.parseInt(caseVars[1])-1;
                    Task um_task = taskList.get(index);
                    um_task.unmark();
                    aftonSpeech("Back again? It seems some things just won't stay buried.");
                    System.err.println(um_task + "\n");
                    break;

                case "todo":
                    taskName = Arrays.stream(caseVars).skip(1).reduce((x,y)-> x + " "+ y)
                                        .orElse("<Corrupted Task>");
                    Task td = new ToDo(taskName);
                    taskList.add(td);
                    aftonSpeech("Another? Let's see how long this one lasts.");
                    System.out.println(td);
                    aftonSpeech(taskList.size() + " entries remain in your little list now.");
                    break;

                case "deadline":
                    String[] dlVars = userInput.split("/by");
                    taskName = dlVars[0].substring(dlVars[0].indexOf(" ") + 1).trim();
                    Task dlTask = new Deadline(taskName, dlVars[1]);
                    taskList.add(dlTask);
                    aftonSpeech("A deadline? How fitting. Time is a luxury most of them didn't have.");
                    System.out.println(dlTask);
                    aftonSpeech("That's " + taskList.size() + " clocks ticking in the dark");
                    break;

                case "event":
                    String[] evVars = userInput.split("(?= /from | /to)");
                    taskName = evVars[0].substring(evVars[0].indexOf(" ") + 1);
                    Task evTask = new Event(taskName, 
                        evVars[1].replace("/from", "").trim(), 
                        evVars[2].replace("/to", "").trim());
                    taskList.add(evTask);
                    aftonSpeech("");
                    System.err.println(evTask);
                    aftonSpeech("That makes " + taskList.size() + " acts to follow.");
                    break;
            
                default:
                    taskList.add(new Task(userInput));
                    listTasks();
                    break;
            }

            userInput = inputScan.nextLine();
        }
        aftonSpeech("Don't think this is over... I always come back.\n" + line);
    }
}

