package purpleguy;

import java.util.Scanner;
/**
 * Represents the UI for the PurpleGuy app
 * Stylises the app to give the effect of the user talking to a digital Afton
 */
public class AftonUI {
    public static final String LINE = "\u2500".repeat(50) + "\n";
    // PurpleGuy Sprite and colours generated by Gemini
    public static final String AFTON_PURPLE = "\u001B[38;2;120;0;200m";
    public static final String DARK_P = "\u001B[48;2;75;0;130m  "; // Deep Purple
    public static final String V_DARK = "\u001B[48;2;48;0;78m  "; // Shadow Purple
    public static final String WHITE = "\u001B[48;2;255;255;255m  ";
    public static final String BLACK = "\u001B[48;2;0;0;0m  ";
    public static final String RESET = "\u001B[0m";
    public static final String S = "  "; //Empty space
    public static final String[] SPRITE = {
        S + S + DARK_P + DARK_P + DARK_P + DARK_P,
        S + DARK_P + DARK_P + DARK_P + DARK_P + DARK_P + DARK_P,
        S + WHITE + BLACK + DARK_P + WHITE + BLACK + DARK_P,
        S + DARK_P + DARK_P + DARK_P + DARK_P + DARK_P + DARK_P,
        S + DARK_P + V_DARK + V_DARK + V_DARK + V_DARK + DARK_P + DARK_P + DARK_P,
        S + S + DARK_P + V_DARK + V_DARK + DARK_P + DARK_P + DARK_P + DARK_P,
        S + S + S + S + S + DARK_P + DARK_P + DARK_P + DARK_P,
        S + DARK_P + DARK_P + DARK_P + DARK_P + DARK_P + DARK_P + DARK_P + DARK_P,
        S + S + S + S + S + DARK_P + DARK_P + DARK_P + DARK_P,
        S + S + DARK_P + DARK_P + DARK_P + DARK_P + DARK_P + DARK_P,
        S + S + S + S + S + DARK_P + DARK_P + DARK_P + DARK_P,
        S + S + S + S + S + DARK_P + DARK_P + DARK_P + DARK_P,
        S + S + S + S + S + DARK_P + S + S + DARK_P,
        S + S + S + S + S + DARK_P + S + S + DARK_P,
        S + S + S + S + S + DARK_P + S + S + DARK_P
    };
    private Scanner scanner;

    public AftonUI() {
        this.scanner = new Scanner(System.in);
    }

    /**
     * Prints the given string in a purple font
     * @param message String to be printed
     */
    public void speak(String message) {
        System.out.println(AFTON_PURPLE + message + RESET);
    }

    /**
     * Initialise the UI by drawing the PurpleGuy sprite and printing greetings
     */
    public void initialise() {
        for (String body : SPRITE) {
            System.out.println(body + RESET);
        }
        speak("You look... familiar. Have we met at the Pizzeria?");
        speak("I'm William. But I suppose you have your own names for me.");
        speak("Tell me... why are you really here?\n");
    }

    public String readInput() {
        return scanner.nextLine().strip();
    }

    public void shutDown() {
        speak("Don't think this is over... I always come back.\n" + LINE);
    }
}
